env: flex
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
  release_app: stake_lane_api
env_variables:
  # Copy it form config/.env-{{ENV}}
beta_settings:
  cloud_sql_instances: "bolao-hub:europe-west1:bolaohub-dev"

