version: '3.7'
services:
  phoenix:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - database
  database:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stake_lane_api_dev
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data:delegated
