version: '3.7'
services:
  database:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bolao_hub_api_dev
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data:delegated

  web:
    image: "bolao_hub_api:latest"
    ports:
      - "8080:4000"
    depends_on:
      - database
      